"""
 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1 == 1

 3 == 1,3

 6 == 1,2,3,6

10 == 1,2,5,10

15 == 1,3,5,15

21 == 1,3,7,21

28 == 1,2,4,7,14,28
We can see that  28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""


def triangle_divisors(target: int) -> int:
    """
    Find the smallest triangular number with more than 'target' divisors.

    A triangular number is the sum of the first n natural numbers (n(n+1)/2).
    This function generates triangular numbers sequentially and counts their divisors
    until finding one with more divisors than the target.

    Args:
        target (int): The minimum number of divisors required (exclusive).

    Returns:
        int: The smallest triangular number with more than 'target' divisors.
    """
    n = 1
    triangle = 1
    divisors = 1
    while divisors <= target:
        n += 1
        triangle += n
        limit = int(triangle**0.5)
        divisors = sum(2 for i in range(1, limit + 1) if triangle % i == 0)
        if limit * limit == triangle:
            divisors -= 1

    return triangle
